### ISSUE TITLE
Consider switching to Electron

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#101]
Because:

- The whole apple-xcode-cocoa-objective-c business is #horror and none of my main skills (I usually have no idea what I'm doing in objective-c
- Electron is cross platform
- Electron has a modern browser engine

Inventory list of Electron features needed to port SoundCleod:

- [x] [Media keys](http://electron.atom.io/docs/v0.37.3/api/accelerator/#available-key-codes)
- [ ] Headphone play/pause (most likely not supported by Electron, [node-hid](https://github.com/node-hid/node-hid/) might be useful)
- [x] Stop on suspend ([powerMonitor](http://electron.atom.io/docs/v0.37.3/api/power-monitor/))
- [x] [Custom userAgent](http://electron.atom.io/docs/v0.28.0/api/browser-window/#webcontentssetuseragentuseragent)
- [x] [Window title changed event](http://electron.atom.io/docs/v0.37.3/api/browser-window/#event-page-title-updated)
- [x] File uploads (does it need to be implemented?)
- [x] Confirm window (does it need to be implemented?)
- [x] [Custom dock menu](http://electron.atom.io/docs/v0.37.3/tutorial/desktop-environment-integration/#custom-dock-menu-os-x)
- [ ] Automatic updates (Squirrel.Mac updates [do not seem to be possible to be hosted on GitHub](https://github.com/Squirrel/Squirrel.Mac#server-support) and the entire UI needs to be implemented "by hand". See also https://github.com/Squirrel/Squirrel.Mac/issues/167)

Deal breakers so far: automatic updates.

**Comment by accatyyc** [comment]
:scream: But Objective-C is the most beautiful language out there!

**Comment by CNLambda** [comment]
Objective-C *isn't* the most beautiful language out there. It's Python (3) and/or Golang. ^^

**Comment by davcamer** [comment]
Swift?

**Comment by CNLambda** [comment]
Isn't that bad, but I do like Python a lot more. I think the reason for that is that I started with python, and I can now just create the language constructs other people find so great about their language within python. But it isn't compilable (at least not with the full feature set, it is a very dynamic), so...

But I would like to have a language having all possibilities like `__add__` and so on, so if you have one that doesn't give the one who's coding in it headaches that persist three times longer than the programmer was even trying to work on the project.

**Comment by jbergstroem** [comment]
Additional pluses:
 - lower barrier of entry for collaborators (javascript)
 - webkit -> v8 means we git bug fixes to engines quicker (not sure if that's relevant to Soundcloud, but yeah)
 - probably easier to implement configuration for things like injecting stylesheets/greasemonkey for people that wants to modify the experience

Regarding autoupdates and Squirrel, [electron suggests](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) [nuts](https://github.com/GitbookIO/nuts) -- that should be able to fit on a free heroku (or most other cloud vm's) plan?

**Comment by salomvary** [comment]
Started playing around with Electron on a [branch](https://github.com/salomvary/soundcleod/tree/electron). First impressions are promising.

**Comment by jbergstroem** [comment]
That's awesome. I'll check it out after work and see if I can contribute.

**Comment by jbergstroem** [comment]
@salomvary: not sure why (just yet), but svg2png segfaults for me with `soundcleod{-lo}.svg` with a segfault (nodejs 6.6.0 on macOS Sierra).

**Comment by jbergstroem** [comment]
Ok, did a quick sample of both processes. WKWebView and Electron performs similarly; both at <1% cpu when streaming. Measuring stack and active threads Electron seems to perform slightly better, but the difference is negligible. Great job so far! Found a few nits (and CMD + L crashes the view) but I would prefer actually forking and fixing.

**Comment by salomvary** [comment]
So I'm done with porting the basic functionality to Electron. As expected switching to Squirrel updater was the most pain in the ass part...

The release candidate / 1.0.0-beta.1 is available here, I'd appreciate feedback before tagging it final and enabling automatic updates from 0.x: 
https://github.com/salomvary/soundcleod/releases/tag/v1.0.0-beta.1

**Comment by jbergstroem** [comment]
@salomvary: tbh it works great for me. I've been running the branch on and off over the week and by looking at your RC notes I feel you have a pretty good insight into what's not working (at the moment). What I haven't tried at all is the updater stuff, nor have I run it in the debugger to see what's going on. I wouldn't call it final (1.0.0) until more feedback lands though. I still haven't had time to dig into sampling but I reckon it's not really needed.

**Comment by jbergstroem** [comment]
@salomvary perhaps mention the soundcleod helper before prompting for admin permissions?

**Comment by salomvary** [comment]
Hmm, what exatly promts for admin? Does it happen on install or later? What does the dialog say?

(I'm not seeing it but my setup might be different. I also installed a million times, might only prompt once?)

**Comment by jbergstroem** [comment]
it said "Soundcleod wants to install a helper" -- happened when I opened the last packaged version of the electron soundcleod version. Can't find anything useful in console :/

**Comment by salomvary** [comment]
Ok, I will look into it. Definitely scary (at least without explanation)...

**Comment by salomvary** [comment]
@jbergstroem where did you run SoundCleod from? Did you copy it to /Applications? Or somewhere else? Or simply from the .dmg file?

**Comment by salomvary** [comment]
..also, are you maybe running it with a user with no admin rights at all?

**Comment by jbergstroem** [comment]
Ran it from downloads folder. "Normal" macOS user.

**Comment by salomvary** [comment]
Fixed in [1.0.0-beta.2](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0-beta.2) (fb79433effafdfd34b9b9ff6351076154dea204d). The problem was trying to install updates on the read-only file system of the dmg image.

It will still present the same prompt when SoundCleod is installed as admin user but run as non-admin and the non-admin user has no write access to the app. If the admin user can escalate rights to admin, automatic updates will be attempted on every new run of SoundCleod. Handling this properly will require some minimal automatic updater UI where users can temporarily/permanently disable automatic updates.

**Comment by salomvary** [comment]
[1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0) is 100% Electron.
