### ISSUE TITLE
Media keys don't work (OS X El Capitan 10.11.4)

### ISSUE THREAD

**Issue by perezperez22** [salomvary/soundcleod#103]
I tried uninstalling and installing Soundcleod again but it doesn't work. Anything I could do about this?

**Comment by r3wn5** [comment]
Yes, I'm facing the same problem. I'm running El Capitan 10.11.5

**Comment by bubske4** [comment]
Same goes for Yosemite 10.10.5. Worked before but was suddenly broken.
I can only press any random media key once (when SoundCleod has focus) and then it ignores every following keypresses

**Comment by salomvary** [comment]
Fixed in 0.19!

**Comment by bubske4** [comment]
Awesome, thanks a lot! Is it possible to have these media keys working when SoundCleod loses focus as well? I am not sure but I thought this was working before this bug came up.

**Comment by r3wn5** [comment]
For me works, no matter where I'm, focused on SoundCleod or not.
Thank you very much, @salomvary!

**Comment by salomvary** [comment]
> Awesome, thanks a lot! Is it possible to have these media keys working when SoundCleod loses focus as well? I am not sure but I thought this was working before this bug came up.

Works for me too, even when not focused.

**Comment by bubske4** [comment]
I don't know what I did wrong before but it works like a charm again :+1: thanks for the quick responses!
