### ISSUE TITLE
Bluetooth Media Controls don't work

### ISSUE THREAD

**Issue by EukaryoteX** [salomvary/soundcleod#104]
I'm not sure if this is related to the other issue involving play/pause on headphones, but with bluetooth headphones, Soundcleod will play, but pressing pause/play, forward, or backward with bluetooth opens iTunes and plays music instead of controlling SoundCleod. 

I can't code, so I don't know how hard the fix is.

**Comment by salomvary** [comment]
Fix landed in 1.3.3
