### ISSUE TITLE
Login with facebook doesn't work

### ISSUE THREAD

**Issue by mimen** [salomvary/soundcleod#109]
On mac os x with chrome as my default browser, trying to login with facebook opens a new tab on my chrome browser which hangs indefinitely.

**Comment by Modulo216** [comment]
Same here, both Facebook and Google login not working.  On OSX Chrome 53.0.2785.116

**Comment by salomvary** [comment]
*Almost* fixed in 1.0.0. When using 1.0.0 the Facebook window goes blank after a successful login but closing SoundCleod and attempting to log in again with Facebook will work.

**Comment by salomvary** [comment]
...probably due to this: https://github.com/electron/electron/issues/7424

**Comment by salomvary** [comment]
Fixed in [1.1.0](https://github.com/salomvary/soundcleod/releases/tag/v1.1.0)

**Comment by slut** [comment]
This is still not working in 1.1.0

**Comment by salomvary** [comment]
Attempted to fix it in the recently released [1.1.1](https://github.com/salomvary/soundcleod/releases/tag/v1.1.1) again. Sorry for the trouble. Programming is hard :)
