### ISSUE TITLE
Only play/pause media key work on macOS Sierra

### ISSUE THREAD

**Issue by rrondeau** [salomvary/soundcleod#110]
Hi,

I'm using the last version of Soundcleod but the previous and next media keys dont seem to be working anymore on Sierra.

Thx again for this software I use everyday !

**Comment by salomvary** [comment]
Hey, fortunately there is an upcoming new version which will hopefully address these issues. If you are brave enough, try out 1.0.0-beta.1 available for download here: https://github.com/salomvary/soundcleod/releases/tag/v1.0.0-beta.1

I'd appreciate any feedback on the new version.

**Comment by rrondeau** [comment]
Thanks, i will try it

**Comment by rrondeau** [comment]
The beta fix my issue, no other problems for the time being.
Thanks again
