### ISSUE TITLE
Add "copy link/open link in browser" on right click

### ISSUE THREAD

**Issue by sindhus** [salomvary/soundcleod#114]
Why is right click on links disabled? It's useful to copy links of tracks when I want to download them.

**Comment by salomvary** [comment]
Good point, will add a copy link/open link in browser option to the right click context menu.

Also note that downloading tracks with the "download" button on soundcloud.com (where the uploader allowed that) should just work (at least in 1.0.0).

**Comment by salomvary** [comment]
Fixed in [1.1.0](https://github.com/salomvary/soundcleod/releases/tag/v1.1.0)
