### ISSUE TITLE
header goes missing sometimes

### ISSUE THREAD

**Issue by sindhus** [salomvary/soundcleod#115]
![screen shot 2016-10-05 at 3 16 47 pm](https://cloud.githubusercontent.com/assets/4291156/19108582/fe2e885a-8b0e-11e6-8e49-f1e866508484.png)

**Comment by jbergstroem** [comment]
@sindhus what version are you using?

**Comment by sindhus** [comment]
@jbergstroem Version 1.0.0 (1.0.0)

**Comment by salomvary** [comment]
I hoped never seeing this again after switching to Chromium :(

@sindhus Do you have any ideas how this could be reproduced? Does it happen after you something specific you do in the app? Or on specific pages? Or just randomly?

What macOS version are you using?

**Comment by jbergstroem** [comment]
I've never been able to reproduce this.

**Comment by sindhus** [comment]
@jbergstroem, @salomvary This happens on a fresh restart of system + app. Should i perhaps just re-install the app?

I uploaded a video of the same [here](https://youtu.be/RPhi1ho9nQo).

**Comment by jbergstroem** [comment]
When you say sometimes, is it for every other page or perhaps during an entire session (meaning you have to restart it)?

**Comment by jbergstroem** [comment]
close as stale?
