### ISSUE TITLE
Clicking on links should use user's default browser

### ISSUE THREAD

**Issue by sunmockyang** [salomvary/soundcleod#117]
Currently any links will open in a new window under the Soundcleod app, except for soundcloud links which just use the open window (which should be the case).

Previous behaviour was that links would open in the default browser which is handy for links like youtube/facebook where the user may already be logged in.

**Comment by sammarcus** [comment]
+1 🙏

**Comment by salomvary** [comment]
Fixed in [1.1.0](https://github.com/salomvary/soundcleod/releases/tag/v1.1.0)
