### ISSUE TITLE
High CPU usage when not minimized

### ISSUE THREAD

**Issue by JackCA** [salomvary/soundcleod#118]
I've been seeing pretty high CPU usage from both of the "Soundcleod helper" processes while a track is playing in the foreground.

When the app is minimized, the CPU usage drops significantly immediately.

I've imbedded the following reproduction:
![high-cpu](https://cloud.githubusercontent.com/assets/296167/19292925/9980662e-8fd4-11e6-85b4-8e40c2445d1f.gif)

I *do* notice a similar pattern when doing the same thing in Chrome itself, so I wonder if it's a lower-level Chromium issue...

**Comment by JackCA** [comment]
this may be related to https://github.com/salomvary/soundcleod/issues/80

**Comment by salomvary** [comment]
I made a little experiment to compare soundcloud.com CPU usage during playback on Chrome and SoundCleod.

The steps of the semi-scientific experiment were the following:

1. Start Activity Monitor, search for "soundcleod"
2. Start SoundCleod (1.1.3-pre.1 built from latest master)
3. Make sure I'm not logged in (log out when necessary and restart from step 2.)
4. Search for "This song is exactly one minute long"
5. On the search results page play the song
6. When testing the "background" scenario, minimize the window
7. When the next song starts playing, switch to Activity Monitor and make a screenshot of the CPU usage columns


Repeat with Chrome, with a few differences:

1. Quit all instances of Chrome
2. Start Activity Monitor, search for "chrome"
3. Start Chrome with a clean user profile: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory=SoundCleodTest https://soundcloud.com`
4. (The remaining steps are the same) 

The results showed no huge difference in CPU usage between SoundCleod and Chrome (both in foreground and background):

Chrome minimized:

<img width="525" alt="chrome-background" src="https://cloud.githubusercontent.com/assets/193923/19722358/a6d67eb4-9b76-11e6-9a56-cf4805ba5667.png">

SoundCleod minimized:

<img width="525" alt="soundcleod-background" src="https://cloud.githubusercontent.com/assets/193923/19722360/a6dad9fa-9b76-11e6-93ed-2ce678bd48c1.png">

Chrome in foreground:

<img width="520" alt="chrome-foreground" src="https://cloud.githubusercontent.com/assets/193923/19722359/a6d95184-9b76-11e6-8f6c-6ad6d9777585.png">

SoundCleod in foreground:
<img width="524" alt="soundcleod-foreground" src="https://cloud.githubusercontent.com/assets/193923/19722362/a6de6746-9b76-11e6-992c-a06e018024cc.png">

If anyone knows a way of making the CPU sampling test automatically repeatable I'd be happy to collect enough samples to have a large enough dataset for statistically valid comparison.

Until that I'd suggest [contacting SoundCloud](https://soundcloud.com/pages/contact) about CPU usage issues.

**Comment by salomvary** [comment]
Btw the high CPU usage is due do SoundCloud doing expensive animations (probably the smooth waveform) during playback.

Chrome/Chromium and therefore SoundCleod as well are clever enough to stop the animations whenever the application is minimized, or to be more precise if no parts of the window are visible on the screen. For example it also does not use high CPU if the window is not minimized but is fully covered by another bigger foreground window.

**Comment by JackCA** [comment]
@salomvary that was my worry (and that lines up with the behavior I see when running in vanilla chrome).

I'm assuming that any sort of "animation disable" option is outside the scope of soundcleod, correct? There's a possibility of hijacking `requestAnimationFrame` but that could be dangerous and have a lot of other repercussions 

Regardless, I will attempt to contact Soundcloud directly.

**Comment by salomvary** [comment]
The only improvement I can imagine on top of what Electron already provides (throttling animations on invisible windows) is to additionally throttle them if the window is not focused. But Electron does not provide an api for that.

**Comment by JackCA** [comment]
@salomvary throttling on our of focus would definitely help a lot but ultimately, I don't think this is a problem you should have to solve.

Soundcloud support told me they have passed my report onto engineers.

I'll update this thread if/when I hear back!
