### ISSUE TITLE
some problems (maybe bugs)

### ISSUE THREAD

**Issue by emadg** [salomvary/soundcleod#126]
In previous versions, I could use command+R to refresh the page and also command+L to show the SoundCloud URL of the track/playlist/artist I am viewing in SondCleod. It looks like these shortcuts are not working anymore in new update.

Also, When I open the app and play a track, before the new update, when I used command+W I could close the window but the song still was playing in the background and I could view the app's GUI by clicking the App's icon in my dock. However, now when I close the window using command+W the song stop playing and I cannot get the app's GUI back by clicking the app's icon. Also when I try to open the app's GUI window again using Sondcleod's options in toolbar using Window->Main Window, I get the error below:

[[A JavaScript error occurred in the main process]]
Uncaught Exception:
TypeError: Cannot read property 'show' of null
    at EventEmitter.menu.events.on (/Applications/SoundCleod.app/Contents/Resources/app.asar/main.js:143:15)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
    at click (/Applications/SoundCleod.app/Contents/Resources/app.asar/menu.js:137:20)
    at MenuItem.click (/Applications/SoundCleod.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/SoundCleod.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)

I am not sure if the previous functionality of command+W was correct or not from the app's design point of view, but I used it a lot for minimizing Soundcleod. If possible please fix these issues so that it works like before.

Thanks ;)

**Comment by salomvary** [comment]
Hey @emadg, first of all thanks for the valuable feedback!

SoundCleod was recently entirely rewritten from scratch (in version 1.x) to support better performance, faster development cycle and hopefully easier code contribution. This introduced a bunch of bugs and missing features, both will soon be addressed (bugs fixed, features reimplemented).
 
- Command+W is supposed to be working as you described, seems to be broken unfortunately :( Will fix it soon, created #128 to keep track of it.
- Command+R went missing for a while but returned in version 1.1.4. You should already have that update, if not it will be installed next time you restart SoundCleod.
- The Cmd+L menu was temporarily removed in 1.x versions to speed up releasing the completely rewritten app. Created #127 to keep track of it.

**Comment by salomvary** [comment]
Command+W is fixed in version 1.1.5.

**Comment by emadg** [comment]
Hi Márton,

Thanks for quick fix of the problem. your app is awesome for listening to
music on Soundcloud.

BTW, the link for version 1.1.5 is not working. I thought it's goof to
notify you.

Cheers,
Emad

**Comment by emadg** [comment]
* it's good to notify you. Sorry for typo. :)

**Comment by salomvary** [comment]
Oops thanks for the heads-up, fixed the download link.

I'm glad you find the app useful. Cheers!
