### ISSUE TITLE
Allow refreshing of homepage

### ISSUE THREAD

**Issue by Impakt** [salomvary/soundcleod#129]
I noticed this with the main soundcloud.com website also. I listen to soundcloud pretty much all week while working and noticed that the home/stream page needs a hard refresh in order for new content to show up sometimes. Unfortunately soundcleod doesnt have a refresh option so i have to restart the entire app for new content to show up.

**Comment by Impakt** [comment]
never mind, found the refresh option on the main menu ,sorry!

**Comment by salomvary** [comment]
Yes, it was added back recently.
