### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by abigpotostew** [salomvary/soundcleod#132]
Using version 1.1.6 on macOS 10.11.3 (15D21)

Activity Monitor is showing CPU usage between 30 and 50% when I'm listening to a set linked below. CPU usage goes down again when I pause the song. SoundCLeod did not do this in the past.

[https://soundcloud.com/t_soundcouncil/podcast-010-leichtigkeit-des-seins-a-time-for-us](https://soundcloud.com/t_soundcouncil/podcast-010-leichtigkeit-des-seins-a-time-for-us)

**Comment by salomvary** [comment]
We've discussed this before on #118. Td;dr: It's not SoundCleod but soundcloud.com causing hight CPU usage, there is not much we can do here :(

The good news is: it's only wasting CPU when the SoundCleod window is visible on the screen.
