### ISSUE TITLE
Feature Request: Album art on media key preview

### ISSUE THREAD

**Issue by kinglime** [salomvary/soundcleod#135]
When pressing the media key to skip to the next track there is a preview in the top right corner showing the track name and the app icon. Instead of using the app icon it should display the album art.
<img width="387" alt="screen shot 2017-03-05 at 3 42 00 pm" src="https://cloud.githubusercontent.com/assets/941516/23591715/769e7c06-01ba-11e7-8aa7-937a9ffaa144.png">

**Comment by kinglime** [comment]
Maybe the image could be extracted from the HTML class="sc-artwork sc-artwork-placeholder-9 image__full g-opacity-transition"

I would attempt this myself but I am not very familiar with JavaScript.

**Comment by kinglime** [comment]
**soundcloud.js**
```javascript
module.exports = class SoundCloud extends Events {
  constructor(window) {
    super()
    this.window = window

    var x = window.document.getElementsByClassName("sc-artwork image__full g-opacity-transition")[0].getAttribute("style");
    var pos1 = x.indexOf("url(") + 4;
    var pos2 = x.indexOf(");") - pos1;
    var image = x.substr(pos1, pos2);
    
    window.on('page-title-updated', debounce((_, title) => {
      this.onTitleUpdated(_, title, image)
    }), titleDebounceWaitMs)
    fixFlakyMediaKeys(window)
  }
```

**main.js**
```
soundcloud.on('play', (title, subtitle, image) => {
    mainWindow.webContents.send('notification', title, subtitle, image)
  })
```

I'm far from a JavaScript/node/electron expert and I couldn't build the project on my machine but perhaps something like this would work?

**Comment by kinglime** [comment]
Was going for something like this: 
<img width="387" alt="modified" src="https://cloud.githubusercontent.com/assets/941516/23592394/c065c636-01c5-11e7-824c-f438a96f8d95.png">

**Comment by kinglime** [comment]
Also relevant: [](https://github.com/hokein/electron-sample-apps/blob/master/notifications/window.js)

**Comment by salomvary** [comment]
@kinglime thanks for the idea and the investigation, definitely sounds like a nice feature. Will add it some time in the future. Also related to #61
