### ISSUE TITLE
Play/Pause touchbar not working

### ISSUE THREAD

**Issue by kinglime** [salomvary/soundcleod#136]
On my touchbar it shows the play media key regardless as to whether or not the music is playing. Pressing the play media key toggles play/pause but the icon doesn't change to the play/pause icon on the touch bar.

**Comment by salomvary** [comment]
Looks like Electron added [TouchBar support](https://github.com/electron/electron/blob/master/docs/api/touch-bar.md) recently.

I don't own a Mac with TouchBar therefore can't promise anything.. Contributions are always welcome:)

**Comment by kinglime** [comment]
@salomvary If you could help me figure out how to build the project I'm sure I could contribute. I'm pretty new to node/electron etc.

**Comment by salomvary** [comment]
@kinglime have you seen the instructions here? https://github.com/salomvary/soundcleod/blob/master/DEVELOPMENT.md#development

Assuming you have Node.js installed and the project cloned locally these commands should be enough to kickstart:
```
npm install
npm start
```

Let me know if it does not work.

**Comment by kinglime** [comment]
I did not see that! That is very helpful. I'll give it a go and report back with my results.

**Comment by kinglime** [comment]
I am working on custom touch bar support [here](https://github.com/kinglime/soundcleod/tree/add-touchbar-support)

<img width="1085" alt="touch bar shot 2017-03-08 at 9 26 38 pm" src="https://cloud.githubusercontent.com/assets/941516/23734671/398f53d8-0446-11e7-89be-eeb6f050208f.png">
<img width="1085" alt="touch bar shot 2017-03-08 at 9 26 48 pm" src="https://cloud.githubusercontent.com/assets/941516/23734670/39717994-0446-11e7-841f-5a9d3e4de682.png">

Here is what I have currently. There are controls for play/pause, previous track, next track and like/dislike (this is based on my pull request). It also displays the song title and artist. I plan to add some nicer looking buttons and incorporate a slider for scrubbing support.

**Comment by kinglime** [comment]
@salomvary Also I have to say Node/Electron/JS is quite fun! Most of my experience is with C++/Java and I've always hated JavaScript but I think I'm really starting to learn.

**Comment by salomvary** [comment]
> I am working on custom touch bar support here

That's pretty cool.

As I have zero experience with developing for and using the Touch Bar I would recommend modeling the behavior and look after iTunes. It is just another audio player like SoundCleod but happens to be built by Apple who certainly have good ideas about how best to interface with their own hardware products :) 

> I've always hated JavaScript but I think I'm really starting to learn.

Good to hear SoundCleod is a fun learning experience for someone!

**Comment by kinglime** [comment]
@salomvary Thanks man I love your app and I hope to contribute as much as I can. I completely agree that we should model iTunes. iTunes has the media controls but it doesn't have the like feature. I really think the like/dislike/undo feature is worth adding to the touchbar. The only difference right now between my implementation and the iTunes implementation is the addition of the scrubbing feature. I am going to try and add this feature. Cheers

**Comment by salomvary** [comment]
Just released 1.3 with Touch Bar support:
https://github.com/salomvary/soundcleod/releases/tag/v1.3.0

\o/

**Comment by rmaes4** [comment]
Just wanted to say that the original issue has been fixed. I think it was fixed in the latest Mac update. Instead of showing the play media key regardless of whether or not soundcleod is playing it now displays a unified play and pause button. This is less confusing for the user. Glad apple fixed it 👍
