### ISSUE TITLE
App will not quit in Fullscreen

### ISSUE THREAD

**Issue by user1432** [salomvary/soundcleod#139]
On OSX 10.12.3. When I open the app in Fullscreen, I can't quit it at all. Command-Q does nothing, and there is no red X circle at the top left corner (it's grayed out), like there is in other fullscreen apps. Not sure what happened, please help.

<img width="1425" alt="screen shot soundcleod fullscreen" src="https://cloud.githubusercontent.com/assets/26334190/23811745/56148158-05a5-11e7-99b2-d2dbc23f0792.png">

**Comment by salomvary** [comment]
Definitely a bug, fix is on the way!

**Comment by user1432** [comment]
Great! Thanks for all your work, the app is fantastic!

**Comment by salomvary** [comment]
Fixed in [1.2.0](https://github.com/salomvary/soundcleod/releases/tag/v1.2.0)
