### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by InitEasyy** [salomvary/soundcleod#142]
Would be nice if we could edit keybinds
ex: i would like to bind forward and back on my mouse to go forward/back a page.

**Comment by salomvary** [comment]
@InitEasyy I assume this has nothing to do with *keyboard* shortcuts, right? (soundcloud.com and SoundCleod already have quite a few keyboard shortcuts, just hit '?' to see them).

Do you mean you want to control back/forward navigation with a mouse that has special back/forward buttons but it does not work with SoundCleod? If that's the case I'd like to know what kind of mouse and what operating system you use and I will check what we can do to support it.

**Comment by salomvary** [comment]
Looks like there is support in Electron for something like that specifically for Windows:
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-app-command-windows

Implementing that on SoundCleod should be quite easy.

**Comment by InitEasyy** [comment]
> I assume this has nothing to do with keyboard shortcuts, right?

Sort of.

> Do you mean you want to control back/forward navigation with a mouse that has special back/forward buttons but it does not work with SoundCleod?

Yes. Steelseries rival and windows 10. I'm talking about the buttons on the side of the mouse. In a web browser it lets me go forward/back a page and being able to use it in soundcleod would be a lot more convenient than ctrl+left arrow or ctrl+right arrow.

**Comment by salomvary** [comment]
Thanks for the clarification, will try to make this work.

**Comment by salomvary** [comment]
@InitEasyy Just released SoundCleod 1.3 which has experimental support for Windows mouse and keyboard Back/Forward/Home buttons.

As I do not own any device with these buttons I implemented the functionality in blind. Any feedback on whether it is working or not would be appreciated.

**Comment by InitEasyy** [comment]
@salomvary Works perfectly! 👍

**Comment by salomvary** [comment]
@InitEasyy Thanks for reporting back on this!
