### ISSUE TITLE
Track preloading for bad connection

### ISSUE THREAD

**Issue by VonSandberg** [salomvary/soundcleod#145]
Hi,
at firtst, thank you for your superb app ;) 
To the topic. I don't know if it would be even possible, but sometimes when I travel and connection is bad, it would be really great if the app could preload one or more tracks ahead. Maybe make it as an option in settings to turn this feature on ... it will be even better :)
Cheers, Jirka

**Comment by salomvary** [comment]
Hey @VonSandberg,

Thanks for writing in, I'm glad you like SoundCleod.

As you might know SoundCleod is just a thin glue between you desktop and soundcloud.com. That means adding features like playback while offline is beyond the goals and capabilities of SoundCleod.

If you live in a country where SoundCloud subscriptions are available, I recommend using their mobile apps with subscription which allows listening to any tracks offline whenever you want.

Cheers!
