### ISSUE TITLE
Shuffle button gone missing

### ISSUE THREAD

**Issue by tyssen** [salomvary/soundcleod#152]
When you go to Collection / Likes the shuffle button next to the view options no longer appears. It used to be there a week or so ago.

**Comment by ErraticFox** [comment]
This app uses the actual SoundCloud website for it's UI so if it's gone, that was SoundClouds decision.

**Comment by tyssen** [comment]
Weird, it's gone from the website now too but when I first posted this issue, it was definitely still there because I reverted to using the website for a few days just so I could use the shuffle feature.

**Comment by ErraticFox** [comment]
That was most likely the website being cached.
