### ISSUE TITLE
Txt is not produced in Documents 

### ISSUE THREAD

**Issue by goldielocknload** [salomvary/soundcleod#158]
Am utilising soundcleod for OBS, it was working fine but I started to get a javascript error. Uninstalled soundcleod, reinstalled and now no text file is present in the Documents folder.

**Comment by salomvary** [comment]
I assume you are using the [modified SoundCleod fork](https://github.com/ErraticFox/soundcleod/releases/tag/1.3.1) by @ErraticFox. If that's the case I suggest you directly get in touch with them as SoundCleod maitained by me does not do anything with your Documents folder. I hope this helps.
