### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by sammarcus** [salomvary/soundcleod#161]
Hi,

I noticed the cache in `~Library/Application Support/SoundCleod/Cache` has ballooned (mine is nearly 1GB), is this expected behavior/are the processes in place to routinely clear this out? I've since excluded it from my backblaze, which is what alerted me to it in the first place, but many (albeit very small) files are several months old. 

Thanks Márton!

**Comment by salomvary** [comment]
That seems to be the HTTP disk cache, where the application caches files downloaded from soundcloud.com for faster load times.

There is no built-in process or user interface element in SoundCleod to clear the cache, deleting the Cache folder should do no harm though.

**Comment by sammarcus** [comment]
Got it! Thanks 😃
