### ISSUE TITLE
Windows 10: Soundcleod hotkeys work even when focused in the Search box

### ISSUE THREAD

**Issue by HyperKids** [salomvary/soundcleod#165]
This is particularly annoying since random tracks are getting randomly reposted and liked when I definitely don't want them to. I believe this is the problem the author of [this issue](https://github.com/salomvary/soundcleod/issues/163) was trying to express.

Thanks for maintaining this project.

**Comment by salomvary** [comment]
Now #163 makes sense:) Thanks for reporting, will investigate!

**Comment by salomvary** [comment]
Fix landed in 1.3.3

**Comment by HyperKids** [comment]
Yay, thank you @salomvary! When will 1.3.3 drop?
