### ISSUE TITLE
History forward/back no longer working

### ISSUE THREAD

**Issue by jakesnake510** [salomvary/soundcleod#168]
Recently the use of command + left arrow/right arrow to navigate back and forth in the application no longer works for me. Any ideas on how I could correct this or if anyone else has had the same issue?

**Comment by jbergstroem** [comment]
I noticed this t he other day as well!

**Comment by salomvary** [comment]
Seems broken for me too, investigating... Meanwhile you can use two finger left/right swipe on macOS to navigate back/forward.

**Comment by jakesnake510** [comment]
Great thanks! Didnt know about this.

**Comment by salomvary** [comment]
Fixed in SoundCleod 1.3.4
