### ISSUE TITLE
Is this still continued?

### ISSUE THREAD

**Issue by jugendhacker** [salomvary/soundcleod#169]
The last commit is from 23rd March and the author isnt responding to PRs and Issues! Is it still in development or is it stoped?

**Comment by salomvary** [comment]
Hello @jugendhacker,

Thanks for asking, the project is still maintained with very limited time available (mostly fixing major bugs).

Will try to respond to your pulll request during the following weeks but I am afraid I can not promise anything.

**Comment by jugendhacker** [comment]
Hi @salomvary,

I know it's very time consuming developing such a project and it's ok for me to hear that you are stillt working on it! I can wait...
