### ISSUE TITLE
Homebrew Cask installation fails!

### ISSUE THREAD

**Issue by ChromaticMind** [salomvary/soundcleod#171]
Hey @salomvary, 

I'm really keen on installing Soundcleod via Homebrew Cask but it keeps failing. I get the following error ->

```error: Swift does not support the SDK 'MacOSX10.12.sdk'```

I am running macOS High Sierra (10.13.6) with Xcode v9.4.1 (9F2000).

Please help :)
Thanks!

**Comment by salomvary** [comment]
Hi @ChromaticMind,

Thanks for writing in! As you probably know Homebrew is an open source project with it's own team of maintainers. As I am not a maintainer of Homebrew or anything SoundCleod related therefore I am afraid I will not be able to help.

You can report a bug to Homebrew Cask here: https://github.com/caskroom/homebrew-cask#reporting-bugs

As a workaround I suggest you install SoundCleod from the Code/Releases tab here on GitHub or from https://soundcleod.com/.
