### ISSUE TITLE
Keyboard controls (play, pause, skip, etc) no longer work

### ISSUE THREAD

**Issue by user1432** [salomvary/soundcleod#174]
Hey guys, just updated my mac to macOS Mojave and realized that keyboard controls no longer work. When I go hit pause or skip, it just brings up iTunes instead. I'm thinking probably because of the new OS? Could we get a fix for this?

**Comment by emadg** [comment]
Hi, I am also experiencing the same issue. The media control buttons (play-pause/next/previous) not working anymore.

**Comment by salomvary** [comment]
Thanks for reporting this! 
I’m on my way back from holidays, will hopefully have time to address Mojave bugs in a couple of days. #solomaintainer

**Comment by salomvary** [comment]
Created a pre-release with latest Electron here: https://github.com/salomvary/soundcleod/releases/tag/v1.4.1-pre.0

As I have not upgraded to Mojave yet, please test and send feedback whether this version fixes the problem.

**Comment by jbergstroem** [comment]
Nope, still broken. I think we should wait for upstream here since I think it's related to #175 as well.

**Comment by electroliquid** [comment]
I am not a programmer, but noticed it when I updated to Mojave on a work computer as well, my guess would be that it is something to do with the new permissions/sandboxing part of the OS that requires explicit permissions in order to have hardware access to anything (such as camera/microphone, etc.).  Will keep my eye open on this feed as I love this app sooooo much!!!!

**Comment by webhamsterz** [comment]
I found the solution on a Deezer forum. Just follow the steps and replace "Deezer" by "Soundcleod" and it will work again. ;) (At least it worked for me)

You have to allow Deezer some accessibility rights.
When I restarted Deezer a second time (...), a security alert warned me that Deezer needed to have "acessibilty" rights. I enabled it and now it works back to normal.

**In case the alert does not show, go to** 
Sytem Preferences
Security and Privacy
Privacy tab
Choose "Accessibility"
Add "Deezer" to the allowed software
(You'll have to unlock the configuration by clicking on the lock and enter your password)

**Comment by salomvary** [comment]
@webhamsterz Thanks for the workaround, I can confirm it works! Documented the workaround on the README and https://soundcleod.com/ until we find a better solution.

**Comment by slnt** [comment]
@webhamsterz's solution worked for me, however a note to others: you'll have to restart SoundCleod for it to work

**Comment by salomvary** [comment]
<img width="532" alt="Screen Shot 2019-04-30 at 11 51 42" src="https://user-images.githubusercontent.com/193923/56954348-de1b8280-6b3e-11e9-987c-331f0f8eb1d8.png">

So I added a dialog that is shown on macOS every time you start SoundCleod and don't have media keys permissions enabled. Will be available soon in the next release.

**Comment by milos-dukic-devinity** [comment]
@webhamsterz it worked for me on Catalina as well thx a million :)

**Comment by LaptopTheOne** [comment]
@webhamsterz it worked for me on Catalina :) thx a million :)

**Comment by dserodio** [comment]
Not working for me on Catalina (10.15.4). Should I file a new issue?

**Comment by salomvary** [comment]
@dserodio There will be a new release soon(ish) addressing all sorts of issues on Catalina.
