### ISSUE TITLE
When closing app on Mojave getting error message

### ISSUE THREAD

**Issue by emadg** [salomvary/soundcleod#175]
Whenever closing the app on macOS Mojave, an error message is shown that "SoundCleod stopped working unexpectedly".

**Comment by jbergstroem** [comment]
Looks like this: https://github.com/electron/electron/issues/8459

I ran into this while looking at updating to electron 3 (cpu usage way down!).

**Comment by salomvary** [comment]
I’m on my way back from holidays, will hopefully be able to address Mojave bugs in a couple of days. #solomaintainer

**Comment by jbergstroem** [comment]
A more recent upstream issue: https://github.com/electron/electron/issues/14837

**Comment by salomvary** [comment]
Created a pre-release with latest Electron here: https://github.com/salomvary/soundcleod/releases/tag/v1.4.1-pre.0

As I have not upgraded to Mojave yet, please test and send feedback whether this version fixes the problem.

**Comment by jbergstroem** [comment]
> Created a pre-release with latest Electron here: https://github.com/salomvary/soundcleod/releases/tag/v1.4.1-pre.0

Nope, still broken.

**Comment by salomvary** [comment]
> Also, worth pointing out:
> 
> > #solomaintainer
> 
> I think you're doing an excellent job.

Thanks, trying to do my best:)

Thanks for trying, will wait for an Electron update then...

**Comment by jbergstroem** [comment]
FWIW, I've tested electron 4 and ran into the same issue. This actually made me revert back to the webview branch. Looks like cpu usage (at least on macos) is equal to electron.

**Comment by salomvary** [comment]
See #174 for workaround.

**Comment by salomvary** [comment]
Should be fixed in 2.0.0.
