### ISSUE TITLE
Sign in modal?

### ISSUE THREAD

**Issue by jbergstroem** [salomvary/soundcleod#176]
While considering the idea of implementing a custom title bar I started thinking about other areas where UI can be improved.

Although sign-in is a rare occurrence, a quite pleasing experience would be having a loading window (instead of the blank window) as well as a separate story for sessionless application starts that has a smaller modal window representing [this page](https://soundcloud.com/signin) (or the modal launched from front page). Thoughts?

**Comment by salomvary** [comment]
Not sure I understand what you are suggesting here... soundcloud.com works without logging in (to some extent) therefore enforcing a "redirect to sign in" is not something we should do in my opinion.

The whole sign-in implementation is quite messy both on soundcloud.com (see how different the email/Facebook/Google flow are) and the code supporting it in SoundCleod (see [hacks here](https://github.com/salomvary/soundcleod/blob/master/app/preload.js#L56-L69) for example), we'd better not add more hacks to the soup.

**Comment by jbergstroem** [comment]
Closing; lets keep soundcleod a "native" experience.
