### ISSUE TITLE
Dark mode ?

### ISSUE THREAD

**Issue by KurushK** [salomvary/soundcleod#177]
Hey
The app the amazing 
As Mojave is released & supports dark mode I think adding dark mode feature to the app would be awesome !
Hope you'll do the needful
Thank & regards

**Comment by salomvary** [comment]
I guess you mean turning soundcloud.com into dark. SoundCleod does not (and will not) aim to modify SoundCloud itself in any means which includes making it dark.

One possible way of doing this would be convincing SoundCloud to add dark mode to their website, which will enable SoundCleod to have proper dark mode too.

**Comment by salomvary** [comment]
Will reopen if/when soundcloud.com adds dark mode.
