### ISSUE TITLE
Playing this file crashes Soundcleod

### ISSUE THREAD

**Issue by dombesz** [salomvary/soundcleod#180]
Mac os: High Sierra 10.13.6
Soundcleod: Version 1.4.0 (1.4.0)

STR:
Playing this track causes Soundcleod to crash.
https://soundcloud.com/clipp_art/jvxta-only-alone-clipp010

**Comment by salomvary** [comment]
Crash confirmed :(

The app logs the following to stdout before crashing:

`2018-12-21 13:37:15.021 SoundCleod[5314:182280] *** Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.20.108/AppKit.subproj/NSCell.m:1650`

**Comment by dombesz** [comment]
Yeah, I suspected it has something to do with the title of the user/track, the username has some funky characters in it.

**Comment by salomvary** [comment]
I suspected that too, but other tracks from the same user are playing fine.

**Comment by salomvary** [comment]
We can try coming up with a minimal reproduction case (a bare minium Electron app that loads the SoundCloud track page in question to causes a crash) and report it in the Electron repo.

**Comment by salomvary** [comment]
Might be the same issue as  #153.

**Comment by jbergstroem** [comment]
FWIW: I tried this in the just-landed electron 5 branch and didn't get a crash.

**Comment by salomvary** [comment]
No more crash in the latest version!
