### ISSUE TITLE
Login is not remembered

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#181]
When logging in with email on macOS the login is not remembered when SoundCleod starts the next time.

**Comment by jbergstroem** [comment]
I use email as well but don't seem to have this problem.

**Comment by salomvary** [comment]
Interesting. I will leave this open until further investigation, it keeps happening for me consistently.

**Comment by szalaiit** [comment]
I can't log in with my gmail account at all. 
I go Sign In -> Continue with Google -> Choose an account -> I click on my account -> Nothing, back to 'Continue with Google

**Comment by jbergstroem** [comment]
This seems fixed when we bump to electron 8 (#193). Works for me at least..

**Comment by jbergstroem** [comment]
@salomvary , @szalaiit can you both try with latest master and see if its fixed?

**Comment by michael-lawrence** [comment]
+1 I'm seeing this issue while using either email or Google. Both are not remembered. I'm using the 1.4.0 release on macOS Mojave (10.14.3).

**Comment by jbergstroem** [comment]
> @michael-lawrence said:
> +1 I'm seeing this issue while using either email or Google. Both are not remembered. I'm using the 1.4.0 release on macOS Mojave (10.14.3).

Are you able to check out master and give it a go?

**Comment by michael-lawrence** [comment]
> > @michael-lawrence said:
> > +1 I'm seeing this issue while using either email or Google. Both are not remembered. I'm using the 1.4.0 release on macOS Mojave (10.14.3).
> 
> Are you able to check out master and give it a go?

Strangely enough, email started working correctly after I left my comment. What's really strange is that it hasn't been working for a few weeks. I have no idea what would have changed to cause it to begin working again.

**Comment by jbergstroem** [comment]
> I have no idea what would have changed to cause it to begin working again.

We're embedding the soundcloud website so there can be lots of reasons.

**Comment by salomvary** [comment]
Seems to be fixed now.
