### ISSUE TITLE
Google login does not work

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#184]
As mentioned [here](https://github.com/salomvary/soundcleod/issues/181#issuecomment-462716751) logging in with Google does not work.

Seems like and issue with Electron: https://github.com/electron/electron/issues/2739 and https://github.com/electron/electron/issues/1865. The [proposed workaround](https://gist.github.com/Gvozd/2cec0c8c510a707854e439fb15c561b0) does not work.

Recommended workaround for SoundCleod users: sign in with email or Facebook.

**Comment by szalaiit** [comment]
Thanks for that!
I was able to login with my gmail account after password reset.
