### ISSUE TITLE
SoundCleod failed to connect to soundcloud.com

### ISSUE THREAD

**Issue by marnovo** [salomvary/soundcleod#185]
Getting this when opening the app, despite allowing the app on macOS firewall and accessibility settings:

> SoundCleod failed to connect to soundcloud.com :(
>
> ERR_ADDRESS_UNREACHABLE
>
> [Try again]

I saw that in the past this was solved by further updates, anything it's possible to do from my end? Thanks!

Versions:

macOS: 10.14.4
SoundCleod: Version 1.4.0 (1.4.0)

**Comment by salomvary** [comment]
@marnovo Is this still happening?

**Comment by marnovo** [comment]
@salomvary actually figured out the reason is [LittleSnitch](https://www.obdev.at/products/littlesnitch/) identified a change in the signature and thus blocked further connections. Not sure if this was intended or not?

**Comment by salomvary** [comment]
That's interesting, thanks for the details. If you downloaded SoundCleod from https://soundcleod.com it should be fine.

I verified a freshly downloaded copy of SoundCleod and it passes the macOS built-in signature checks:

```
$ codesign --verify --verbose /Applications/SoundCleod.app
/Applications/SoundCleod.app: valid on disk
/Applications/SoundCleod.app: satisfies its Designated Requirement
```

If `codesign` does not pass the check I suggest you reinstall SoundCleod from soundcleod.com. If the problem persists it is an issue with LittleSnitch and not with SoundCleod.

I hope this helps!
