### ISSUE TITLE
Possibility to disable Microphone

### ISSUE THREAD

**Issue by jsi-p** [salomvary/soundcleod#188]
When starting SoundCleod I get a dialog saying "SoundCleod is using your Microphone Allow/Stop". Pressing Stop also stops SoundCleod. This is identical to what happens with Chrome when a website requires Microphone.

Would it be possible to have an option (any kind of Option will do) to disable Microphone if there is no need for it?

**Comment by salomvary** [comment]
Hi @jsi-p, thanks for reporting this issue! Sounds very weird as SoundCleod does (should) not need the microphone at all. What operating system (and what version of it) are you using? What is your version of SoundCleod?

**Comment by jsi-p** [comment]
I have macOS 10.13.6. SoundCleod version is 1.4.0.

**Comment by salomvary** [comment]
That sounds very weird. If you installed SoundCleod from https://soundcleod.com/ this should not happen.

Do you get prompted for microphone access if you use SoundCloud in Chrome?

**Comment by jsi-p** [comment]
Well actually Chrome doesn't ask when going to soundcloud.com. And seems like now SoundCleod doesn't ask it anymore. I did reinstall SoundCleod, though, so I'm not sure if soundcloud.com stopped asking for the microphone, or whether reinstall helped :)

Thanks anyways. I think this issue can be closed, since the problem disappeared.

**Comment by jsi-p** [comment]
I just realized it was Sophos which warned about Chrome (and SoundCleod) using the microphone. And now the popups have returned. I even got a screenshot of one, so I can paste it here.

**Comment by jsi-p** [comment]
![Screen Shot 2019-05-10 at 14 19 03](https://user-images.githubusercontent.com/11882778/57524350-39642680-7330-11e9-95c6-6d69c234eb0b.png)

**Comment by jsi-p** [comment]
https://support.home.sophos.com/hc/en-us/articles/360000163143-Setting-Privacy-Guard-exceptions

"Privacy Guard is a Sophos Home Premium feature that protects against unwanted use of the webcam and microphone of your computer. Sophos Home notifies you when a non-Apple signed application that uses a camera and microphone is launched."

**Comment by salomvary** [comment]
@jsi-p thanks for the update! I *think* this is a false alarm from Sophos. SoundCleod is indeed signed with a non-Apple certificate (which would cost me $99 / year) and the underlying engine (Electron) is potentially capable of using the microphone. However I *think* it is not able to use the microphone without an explicit permission request, which means if SoundCleod or soundcloud.com would ever actually try to use the microphone you will have to allow or deny that.

As I am 99.9% sure SoundCleod is currently *not using* the microphone (ie. listening or recording any audio) I suggest you reach out to Sophos to refine their warning to something like "SoundCleod is capable of using the Microphone". I believe it is also fine to permanently deny microphone access in this case.

**Comment by salomvary** [comment]
I figured it is actually impossible to capture audio with Electron:
https://electronjs.org/docs/api/desktop-capturer#caveats
