### ISSUE TITLE
1.4.1-release?

### ISSUE THREAD

**Issue by jbergstroem** [salomvary/soundcleod#192]
Release checklist:

- [x] Fix the broken accessibility settings prompt https://github.com/electron/electron/issues/20787
- [x] Even if accessibility settings are enabled, Electron does not seem to call the registered `MediaPlayPause` handler https://github.com/electron/electron/issues/20788
- [x] Since SoundCloud and Electron both support the native [MediaSession API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) figure out if/how that conflicts with our own custom media keys bindings
- [x] Build app with new code sign certificate
- [ ] Also sign the app with the old expired certificate
- [ ] Add a "pivot version" to the update server

**Comment by salomvary** [comment]
It's on my list.. What keeps me away is the 20+ step task of replacing the self-signed code signing certificate that expired last October:/

**Comment by salomvary** [comment]
@jbergstroem seems like the Electron@7 upgrade won't be an easy ride, see the checklist I added in the description above.

**Comment by salomvary** [comment]
Another idea worth exploring: remove custom media keys glue and see if things work with the MediaSession API only, both on Windows and macOS.

**Comment by jbergstroem** [comment]
> Another idea worth exploring: remove custom media keys glue and see if things work with the MediaSession API only, both on Windows and macOS.

What about doing it in two steps? Since mediakeys are already pretty broken, how about an incremental release without it (to fix other bugs and get performance improvements), then a feature release with whatever media keys path we take?

**Comment by salomvary** [comment]
Yeah, maybe. Found a few more things broken:

- Controlling MediaSession API  with media keys does not work when the screen is locked (this does work with "native media keys")
- Might or might not be related but stopping playback when the computer goes to suspend is also broken

**Comment by Jendker** [comment]
Is there any easy way of building the app by yourself if currently app signing is the problem to get the new release?

**Comment by salomvary** [comment]
@Jendker check out https://github.com/salomvary/soundcleod/blob/master/DEVELOPMENT.md

**Comment by salomvary** [comment]
Late but not too late, new version is out!
