### ISSUE TITLE
deps bump: Electron 7

### ISSUE THREAD

**Issue by jbergstroem** [salomvary/soundcleod#193]
Tracking issue for updating to to the 6.x (I have a local branch with some test issues) ecosystem.

**Comment by salomvary** [comment]
Thanks! Feel free to push the work-in-progress branch into a pull request!

**Comment by jbergstroem** [comment]
This looks very suspicious: https://github.com/electron-userland/spectron/issues/443

**Comment by jbergstroem** [comment]
I've updated to 8 now and reverted the spectron bumps, seems to pass for me locally at least.

**Comment by jbergstroem** [comment]
Landed in 68035c7796208e613599e33c81acd9ca36c057ee.
