### ISSUE TITLE
Images not loading via VPN

### ISSUE THREAD

**Issue by alexwolf22** [salomvary/soundcleod#208]
I just downloaded this via brew cask and the images in the app don't seem to be loading 

![image](https://user-images.githubusercontent.com/17020909/85192611-2c369c80-b291-11ea-8cfc-f6357d661f9a.png)

**Comment by alexwolf22** [comment]
So I have a VPN on and when I turned it off the images loaded. Is there a way around this?

**Comment by salomvary** [comment]
@alexwolf22 Does the same issue happen when using soundcloud.com in Chrome? Did you try turning on the VPN and *then* restarting SoundCleod?

**Comment by alexwolf22** [comment]
Hmm seems to be working now on the SoundCleud app too. 

I remember a few times I had issues when images rendering on the chrome page. 

The VPN I have connects to a lot of different countries/ regions randomly, so it's possible in certain countries Soundcloud permits image loading or something.
