### ISSUE TITLE
OBS text file output support

### ISSUE THREAD

**Issue by chriscolomb** [salomvary/soundcleod#214]
Hello! I was wondering if the newest version of SoundCleod can support the output of a UTF-8 text value which displays the song playing's title. I saw that it was supported on 1.3.1 (https://github.com/ErraticFox/soundcleod/releases) However, this one is quite buggy, and the songs don't play most of the time.

Thank you in advance.

**Comment by salomvary** [comment]
Hi! I assume you are using the [modified SoundCleod fork](https://github.com/ErraticFox/soundcleod/releases/tag/1.3.1) by @ErraticFox. If that's the case I suggest you directly get in touch with them as the original SoundCleod maitained by me does not have OBS support at all.
