### ISSUE TITLE
Some soundcloud songs have no sound.

### ISSUE THREAD

**Issue by fencehopping** [salomvary/soundcleod#218]
Some of the songs in my soundcleod playlist have no sound when played through the app, like this one:
https://soundcloud.com/lilo_key/jack-harlow-drip-drop-keymix

**Comment by salomvary** [comment]
@fencehopping That tracks plays for me just fine. What version of SoundCleod do you have? What operating system do you use?

**Comment by fencehopping** [comment]
Thanks for the response! I'm using version 1.3.19 on Windows 10 Pro

It's very strange, so far a handful of tracks have had no sound, but when played through just the soundcloud page, they work fine.

**Comment by salomvary** [comment]
Please install latest SoundCleod (2.0.0) and try again. Let me know if the problem still persists!
