### ISSUE TITLE
[Feature Request] Discord Integration

### ISSUE THREAD

**Issue by zvbt** [salomvary/soundcleod#236]
A discord rich presence integration to show people what you listening to

**Comment by Impakt** [comment]
i dont think discord has the functionality for that.

**Comment by zvbt** [comment]
yes it is called Rich Presence on the developer page

**Comment by Impakt** [comment]
https://github.com/salomvary/soundcleod/pull/237

**Comment by Impakt** [comment]
I have no idea how to test it though
