### ISSUE TITLE
Refresh with Cmd+R and a menu item

### ISSUE THREAD

**Issue by farfromrefug** [salomvary/soundcleod#31]
I cant seem to find a way to refresh the page (get new content).
Any way of doing this?

Thanks

**Comment by sunmockyang** [comment]
Could we reopen this issue? Or create a new one related to it?

**Comment by salomvary** [comment]
Why and how often do you have to reload?

**Comment by sunmockyang** [comment]
Not often, but once in a while I'll have a network issue and I'll download half the page. Since some of the pages don't have an easy way to reload I have to go back forwards in my history.

________________________________

**Comment by sunmockyang** [comment]
<img width="616" alt="screen shot 2016-10-28 at 1 48 36 pm" src="https://cloud.githubusercontent.com/assets/2775774/19816463/5b6c9a58-9d15-11e6-9dda-718dfca7de2a.png">
Like here the waveforms/comments are not showing up

**Comment by sunmockyang** [comment]
And also when I leave and come back after a while to the home page, I want to see what new tracks have been posted so I want to refresh the page

________________________________

**Comment by jasonseney** [comment]
I'd like to bump this up as well - I tend to refresh many times per day to listen to the latest tracks in my feed. Right now, to get new songs we need to restart Soundcleod. : )

**Comment by salomvary** [comment]
Yup, it will go live with the next release.
