### ISSUE TITLE
Update SPMediaKeyTap

### ISSUE THREAD

**Issue by shamrin** [salomvary/soundcleod#42]
E.g., I can't run soundcleod together with [yandex-music-mac-player][yaapp] (Mac app for [Yandex.Music][ya], music service for Russia).

Updating SPMediaKeyTap should fix it, bringing in [whitelist changes][1].

[ya]: http://music.yandex.ru
[yaapp]: https://github.com/mblsha/yandex-music-mac-player
[1]: https://github.com/nevyn/SPMediaKeyTap/blob/master/SPMediaKeyTap.m#L146-L150

**Comment by Skinner927** [comment]
+1 only the play/pause media key works my USB keyboard. Newer versions of SPMediaKeyTap work fine.
