### ISSUE TITLE
[Feature] Save state between sessions

### ISSUE THREAD

**Issue by franciscolourenco** [salomvary/soundcleod#50]
Would be nice to come back to the same place where SoundCleod was when the application was closed.

**Comment by jbergstroem** [comment]
Perhaps I'm misunderstanding but I feel state is recognized (at lesat what track and how far, etc) via upstream. Close?

**Comment by salomvary** [comment]
Yup. Also given the bandwidth I have for new features and the amount of contributions this is unlikely to happen in SoundCleod any time soon.
