### ISSUE TITLE
show warning when no flash is detected

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#51]
As proposed in #48. Should be unobtrusive, would be great to optionally launch Safari with the flash download/install page.

**Comment by doitdada** [comment]
Please remove this warning, have never had an issue with sound not playing because of the lack of Flash plugin.

Its 2015, Flash is only used by old newspapers trying to stream video.

**Comment by salomvary** [comment]
> Please remove this warning, have never had an issue with sound not playing because of the lack of Flash plugin.
> 
> Its 2015, Flash is only used by old newspapers trying to stream video or ads.

Playing certain tracks on soundcloud.com still needs Flash. (It is true that most of them don't.)

> To satisfy both parties, just add a "Do not bug me anymore" button.

That would result in those users who hit "Do not bug me anymore" writing bug reports a little later about broken playback (when they have forgotten about the warning they dismissed).

Installing/updating Flash once every few months is not a huge price to pay. Dismissing the warning once per SoundCleod startup is also a fairly little inconvenience if you are really really against Flash.

**Comment by doitdada** [comment]
Its time to cut the cord?
