### ISSUE TITLE
Sign in with G+ doesn't work

### ISSUE THREAD

**Issue by herval** [salomvary/soundcleod#53]
(nothing happens when you click the button)

**Comment by mttkay** [comment]
:+1: 

Can't log into my account :(

**Comment by salomvary** [comment]
Yeah, I know it's a pain. Unfortunately not trivial to support, thanks to soundcloud.com opening popups opening other popups, etc.

Will try to look into it in the near future unless someone wants to volunteer..

**Comment by salomvary** [comment]
Started some work in [fix-google-login](https://github.com/salomvary/soundcleod/tree/fix-google-login), still no success. Apparently making G+ popups work requires proper handling of window-and-it's-opener relations and opening windows by name on javascript level which seems to be nearly impossible on Cocoa/WebView. Especially making `window.open('some url', 'name of an existing window')` scenario work as expected.

**Comment by salomvary** [comment]
Fixed in [1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0).
