### ISSUE TITLE
Use WKWebView on Yosemite instead of WebView

### ISSUE THREAD

**Issue by erichoracek** [salomvary/soundcleod#66]
The performance of SoundCleod on Yosemite is pretty unfortunate. I think the performance issues would be largely fixed if you migrated from `WebView` to `WKWebView`, introduced in Yosemite 10.10. Unfortunately, this would require supporting both assuming you'd like for SoundCleod to stay backwards compatible with prior OS X releases.

**Comment by uchuugaka** [comment]
Although you are forced to rely on JavaScript in WKWebView for a lot the functionality that is exposed as Objective-C in WebView.

**Comment by salomvary** [comment]
This will not happen, we are moving away from Objective-C/Cocoa by switching to Electron. See https://github.com/salomvary/soundcleod/issues/101 and https://github.com/salomvary/soundcleod/releases/tag/v1.0.0-beta.1.
