### ISSUE TITLE
Menu for history back-forward navigation

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#67]
Something like in Chrome? (Note: Cmd + left/right already works.)

![screenshot 2014-11-05 14 33 03](https://cloud.githubusercontent.com/assets/193923/4918363/4c39a968-64f0-11e4-9034-3ce5a8f513a7.png)

**Comment by smeador** [comment]
+1

**Comment by smeador** [comment]
For what it's worth, I just discovered that Command+left/right arrow take you back and forward.

**Comment by sammarcus** [comment]
:+1:

**Comment by salomvary** [comment]
Added in 0.18
