### ISSUE TITLE
Crash (SIGSEGV)

### ISSUE THREAD

**Issue by dserodio** [salomvary/soundcleod#73]
SoundCleod has been crashing a lot lately. Here's the beginning of the latest crash report. Should I send the full crash report somewhere?

    Process:         SoundCleod [41012]
    Path:            /Applications/SoundCleod.app/Contents/MacOS/SoundCleod
    Identifier:      sc.SoundCleod
    Version:         0.17 (0.17)
    Code Type:       X86-64 (Native)
    Parent Process:  launchd [281]
    Responsible:     SoundCleod [41012]
    User ID:         1508410026

    Date/Time:       2015-01-09 19:13:23.298 -0200
    OS Version:      Mac OS X 10.9 (13A3017)
    Report Version:  11
    Anonymous UUID:  F8519AEA-D987-1DA0-90A5-E9BAD55AD52B

    Sleep/Wake UUID: B427091A-BB3B-4010-B5DE-F557721B1A9A

    Crashed Thread:  3  com.apple.NSURLConnectionLoader

    Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
    Exception Codes: KERN_INVALID_ADDRESS at 0x00000000bbadbeef

    VM Regions Near 0xbbadbeef:
    --> 
        __TEXT                 000000010245a000-000000010246a000 [   64K] r-x/rwx SM=COW  /Applications/SoundCleod.app/Contents/MacOS/SoundCleod

**Comment by salomvary** [comment]
Could you share the dump/report on dropbox or create a gist?

**Comment by dserodio** [comment]
I think it's too big for a Gist, so here it is: https://dl.dropboxusercontent.com/u/3087675/SoundCleod_2015-01-09-191327_L-BRZH71BFH0-M.crash.gz

**Comment by salomvary** [comment]
Should not happen anymore in [1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0).
