### ISSUE TITLE
EXC_GUARD Exceptions (Crash)

### ISSUE THREAD

**Issue by jordanandree** [salomvary/soundcleod#74]
I get these crashes on startup or when clicking on a song or profile ... usually 2-3 times in succession before the app will actually load and be stable. 

Here is a Gist of the dump: https://gist.github.com/jordanandree/4924576c930de8c45bb7

**Comment by salomvary** [comment]
Thanks for the dump, had a quick look but I have no idea why this is happening.. Will try reproducing on Yosemite.

**Comment by salomvary** [comment]
Should not happen anymore in [1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0).
