### ISSUE TITLE
Heavy CPU load in OS X 10.10.2

### ISSUE THREAD

**Issue by julian-weinert** [salomvary/soundcleod#80]
I discovered heavy CPU load of 50 to 100 percent on one core during playback in 10.10.2 on a MacBookPro11,2.

Would you need any further info, process analysis, or similar?

**Comment by salomvary** [comment]
Thanks for reporting. If it's reliably reproducible, would you mind giving detailed instructions? Does the same happen when using soundcloud.com in Safari?

**Comment by frowing** [comment]
@salomvary I'm seeing the same issue on 10.10.4. The same CPU load does not happen when you open SoundCloud on Safari.

**Comment by eugenet8k** [comment]
Having the same issue at Mac OS El Capitan 10.11.1 on MBP 13" Retina. CPU constantly at about 70%, but it works fine in native Safari.

<img width="846" alt="El Capitan" src="https://cloud.githubusercontent.com/assets/4804824/11572712/849a50ee-99b7-11e5-9862-08376518db82.png">

**Comment by warcher123** [comment]
I'm having the same issues on my MacBook Pro 13" Retina, running 10.11.2.
It's working fine in Safari, but use of SoundCleod unfortunately is impossible like this.

<img width="1226" alt="bildschirmfoto 2016-02-06 um 9 42 13 am" src="https://cloud.githubusercontent.com/assets/17095452/12865794/ee68b416-ccb6-11e5-8bda-ae360f0a1887.png">

**Comment by jbergstroem** [comment]
Can confirm on Sierra with Safari technology preview (system webcore is linked to preview, right?)

**Comment by jbergstroem** [comment]
(answering to above: nope)

Just tested the wkwebkitview branch and linked it specifically to the safari technology preview. I'm currently sitting at ~10-15% cpu which then drops to ~2% cpu after a while. Thinking the 'spike' is buffering-related but I haven't really looked into it.

**Comment by salomvary** [comment]
So that's kinda good news, isn't it?

**Comment by salomvary** [comment]
Should be fixed in [1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0). If not, please reopen.
