### ISSUE TITLE
Feature request, audio EQ settings

### ISSUE THREAD

**Issue by Nosanon** [salomvary/soundcleod#83]
I'm loving this app but my speakers are not so good so I want the ability for simple equalizer tuning. I found this workaround http://www.dctrwatson.com/2011/06/os-x-system-equalizer/ but it would be great if it was a feature. Thanks again for the great app!

**Comment by salomvary** [comment]
SoundCleod is not meant to enhance hardware audio capabilities neither features (or lack of them) on soundcloud.com. I think you should stick with a third party solution.
