### ISSUE TITLE
Replacement icon for Yosemite

### ISSUE THREAD

**Issue by hacknug** [salomvary/soundcleod#84]
I made a replacement icon for Soundcleod to use it on Yosemite. I know maybe the reason why the app didn't use SoundCloud's logo is becuse of copyright things and all that stuff, but since I already did it for me, I thought maybe it would be better to let you know just in case someone wanted to use it.

This is how it looks in my dock:
![SoundCleod Replacement Icon](https://cloud.githubusercontent.com/assets/1107521/8060558/585361dc-0ec6-11e5-93b7-1d0d5531fe9c.png)

I hope no one feels offended by this. I really love SoundCleod and I'm extremely thankful for it. I could also make a similar icon with the original cloud from the app. Let me know if any of you is interested on something like this.

Here's a link to download the icon: http://1drv.ms/1FOEZda

**Comment by sammarcus** [comment]
Awesome! Thanks, @hacknug ! :+1:

**Comment by salomvary** [comment]
Hello @hacknug,

Nice initiative, consistent design for all the things! I'm not familiar with Yosemite icon guidelines, I guess they should be circular with white border, or something like that.

However
- Please do not use SoundCloud's original icon. We are using a different cloud (actually the unicode cloud symbol ☁) to differentiate from any (future and past) official app by SoundCloud.com. It might also have copyright implications.
- Please provide originals in svg format both for high and low resolution (down to 16x16 px). No need to create all the possible sizes, we have a [script](https://github.com/salomvary/soundcleod/blob/master/generate-images.js) that generates them from the two svg files.

For the best results, please modify the original svgs for [high](https://github.com/salomvary/soundcleod/blob/master/soundcleod.svg) and [low resolution](https://github.com/salomvary/soundcleod/blob/master/soundcleod-lo.svg).

**Comment by hacknug** [comment]
Okay, I've generated 1024px versions in both SVG and PNG plus the .icons file of both the Unicode and the SoundCloud version.

As I'm writing this I'm noticing that it's probable the character you posted looks different than what I saw. Here's how the new version looks:

![unicode](https://cloud.githubusercontent.com/assets/1107521/8084514/adc1a5e6-0f8b-11e5-899a-88220cb372c2.png)

**Comment by mike-u** [comment]
Could we make a circular white border icon with the unicode cloud? I think that would look the best.

**Comment by hacknug** [comment]
You can download all three options I made from this link. Just let me know if there's anything else you need.

http://1drv.ms/1IO8qUz

**Comment by mike-u** [comment]
I really like this one, I wish we could use it officially:
![arialpng](https://cloud.githubusercontent.com/assets/8935879/11769864/7401e944-a1bf-11e5-9a25-963349d24c02.png)

**Comment by salomvary** [comment]
I decided to keep the old square logo beacuse:
- It's part of the "brand".
- No Apple design guidelines require rounded icons.
- Other Mac apps are also look fine with non-rounded icons (eg. https://github.com/macvim-dev).
- [StreamCloud](http://streamcloud.cc/) uses a very similar icon to the one proposed here. 
- If there was an official SoundCloud Mac app, that would most likely use a very similar rounded icon too.
