### ISSUE TITLE
"Adobe Flash required to play this track"

### ISSUE THREAD

**Issue by obimod** [salomvary/soundcleod#85]
You need Adobe Flash to play this track.
Please install Flash and reload the page.

---

Seems like this is the root cause for me needing to "skip" every other song.

**Comment by obimod** [comment]
OS X v10.9.5
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	8 GB

**Comment by salomvary** [comment]
Which track?
Which SoundCleod version? (Menu -> SoundCleod -> About to check)

**Comment by obimod** [comment]
Haven't noticed it since. Closing.
