### ISSUE TITLE
Feature request: Likes export

### ISSUE THREAD

**Issue by deepdeviant** [salomvary/soundcleod#87]
Will be cool to have feature to export playlists and especially Likes. 
Anyway the app is great, thank you.

**Comment by salomvary** [comment]
SoundCleod is not meant to "enhance" or add functionality to soundcloud.com.

Btw. soundcloud.com has a [public api](https://developers.soundcloud.com/docs) which enables any third party developer to build this functionality in question. It might already exist or you can build it yourself:)
