### ISSUE TITLE
Hitting << on first track in stream does nothing

### ISSUE THREAD

**Issue by Qix-** [salomvary/soundcleod#88]
When I am looking at my 'Likes' stream, sometimes I want to go back to the very beginning of the stream.

It's small, but hitting the `<<` key on my mac's keyboard doesn't restart the song (try out Spotify and you'll see what I mean). If there is no track before the one playing, pressing the button does nothing.

**Comment by salomvary** [comment]
This is not a bug in SoundCleod, sounds more like a feature request for soundcloud.com. Check this out:
https://www.soundcloudcommunity.com/soundcloud/topics/about-feature-requests
