### ISSUE TITLE
Lowercase "s" keypress not recognized

### ISSUE THREAD

**Issue by hi-phi** [salomvary/soundcleod#89]
It doesn't matter where in the app, lowercase "s" keyboard input is not working for me.
Also if the focus is on the app, e.g. Spotlight while focus on Soundcleod doesn't let me type "s".
Uppercase is working fine.

I'm on Yosemite 10.10.2, MacBook Pro Early 2011, US keyboard

**Comment by salomvary** [comment]
Works for me, also nobody else reported this. Closing for now, feel free to reopen if still happening.
