### ISSUE TITLE
Weirdness on OSX Mountain Lion 10.8.5

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#93]
![csv2fx1wsaegx2i](https://cloud.githubusercontent.com/assets/193923/10870775/4a0c97ea-80d3-11e5-84b2-9c675305c77b.png)

**Comment by pretty** [comment]
I'm seeing the same

**Comment by salomvary** [comment]
Should be fixed in [1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0).
