### ISSUE TITLE
0.18 Error: You need Adobe Flash Player to play this track.

### ISSUE THREAD

**Issue by ldiqual** [salomvary/soundcleod#98]
This error started to appear today: 

![image](https://cloud.githubusercontent.com/assets/941453/12560958/50148636-c352-11e5-982f-cd97f48207e7.png)

Probably a SC update?

**Comment by salomvary** [comment]
Yep, saw this. Will have a look.

**Comment by salomvary** [comment]
Looks like no longer happening. Probably a glitch on soundcloud.com.
