### ISSUE TITLE
Update Sparkle (>=1.13.1)

### ISSUE THREAD

**Issue by DavidGoldman** [salomvary/soundcleod#99]
Not sure if this project is affected (is everything served under HTTPS?). See the [Sparkle vulnerability](https://github.com/sparkle-project/Sparkle/issues/720).

**Comment by salomvary** [comment]
Looks like SoundCleod is safe:

> Applications using Sparkle with HTTPS appcast feed URLs and HTTPS release notes links (if any) are safe.

We use https appcast and no release notes links:
https://github.com/salomvary/soundcleod/blob/e47b58f0c051391a647b3b16139b237b2354d7ea/SoundCleod/SoundCleod-Info.plist#L47

Will update anyway.

**Comment by andrewb273** [comment]
@salomvary Awesome, you rock!

**Comment by salomvary** [comment]
0.20 updates Sparkle to 1.14.0
